export const Members = [
    {
        status: "active",
        date: "10/11/2022",
        users: [
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
        ],
    },
    {
        status: "active",
        date: "10/12/2022",
        users: [
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
        ],
    },
    {
        status: "active",
        date: "10/12/2022",
        users: [
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
        ],
    },
    {
        status: "active",
        date: "09/12/2022",
        users: [
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
        ],
    },
    {
        status: "active",
        date: "10/12/2022",
        users: [
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
        ],
    },
    {
        status: "active",
        date: "10/12/2022",
        users: [
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
            "LorenIpsumLorenIpsum",
        ],
    },
];